services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - user-service
      - notification-service
      - regulation-service
    networks:
      - app-network
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./services/auth-service/.env
    restart: unless-stopped
    networks:
      - app-network
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "5001:5001"
    env_file:
      - ./services/user-service/.env
    restart: unless-stopped
    networks:
      - app-network
  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    ports:
      - "5003:5003"
    env_file:
      - ./services/notification-service/.env
    restart: unless-stopped
    networks:
      - app-network
  regulation-service:
    build: ./services/regulation-service  
    container_name: regulation-service
    ports:
      - "5004:5004"
    env_file:
      - ./services/regulation-service/.env
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge